apiVersion: v1
kind: Service
metadata:
  name: simple-server-a
  labels:
    app.kubernetes.io/name: simple-server-a
    app.kubernetes.io/component: yolo
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app.kubernetes.io/name: simple-server-a
    app.kubernetes.io/component: yolo
