apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: datanode
  labels:
    app: datanode
spec:
  selector:
    matchLabels:
      app: datanode
  serviceName: "datanode"
  replicas: 2
  template:
    metadata:
      labels:
        app: datanode
    spec:
      containers:
      - name: datanode
        image: bde2020/hadoop-datanode
        imagePullPolicy: IfNotPresent
        env:
          - name: CORE_CONF_fs_defaultFS
            value: hdfs://namenode:8020
        volumeMounts:
        - name: hdfs-data
          mountPath: /hadoop/dfs/data
  volumeClaimTemplates:
  - metadata:
      name: hdfs-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: default
      resources:
        requests:
          storage: 175M
