# Service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark
  namespace: spark-space

---

# Role in sparkspace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: spark-space
  name: pod-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]