apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-server
  labels:
    app.kubernetes.io/name: simple-server
    app.kubernetes.io/component: yolo
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: simple-server
      app.kubernetes.io/component: yolo
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: simple-server
        app.kubernetes.io/component: yolo
    spec:
      containers:
        - name: simple-server-a
          image: bkenna/simple-server-app
          command:
            - /usr/local/bin/node
          args:
            - index.js
            - --server
            - Server-A
            - --port
            - "8000"
          ports:
            - containerPort: 8000
          resources:
            limits:
              memory: 200M
              cpu: "2"
        - name: simple-server-b
          image: bkenna/simple-server-app
          command:
            - /usr/local/bin/node
          args:
            - index.js
            - --server
            - Server-B
            - --port
            - "8001"
          ports:
            - containerPort: 8001
          resources:
            limits:
              memory: 200M
              cpu: "2"
        - name: simple-server-c
          image: bkenna/simple-server-app
          command:
            - /usr/local/bin/node
          args:
            - index.js
            - --server
            - YOLO
            - --port
            - "8002"
          ports:
            - containerPort: 8002
          resources:
            limits:
              memory: 200M
              cpu: "2"