# type: LoadBalancer | ClusterIP | NodePort
apiVersion: v1
kind: Service
metadata:
  name: task-manager
spec:
  selector:
    app: task-manager
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer