apiVersion: v1
kind: Service
metadata:
  name: simple-server
  labels:
    app.kubernetes.io/name: simple-server
    app.kubernetes.io/component: yolo
spec:
  ports:
  - port: 8000
    targetPort: 8000
  - port: 8001
    targetPort: 8001
  - port: 8002
    targetPort: 8002
  selector:
    app.kubernetes.io/name: simple-server
    app.kubernetes.io/component: yolo
