# Name Node
apiVersion: v1
kind: PersistentVolume
metadata:
  name: namenode-pv
  labels:
      type: namenode
spec:
  capacity:
    storage: 200M
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: default
  hostPath:
      path: "/home/bren/data/nameNode"

---

# Name Node Claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hdfs-name
spec:
  selector:
    matchLabels:
      type: namenode
  accessModes:
  - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 175M

---

# Data Node-1
apiVersion: v1
kind: PersistentVolume
metadata:
  name: datanode-vol1-pv
  labels:
      type: datanode-vol1
spec:
  capacity:
    storage: 200M
  accessModes:
    - ReadWriteOnce
  storageClassName: default
  hostPath:
      path: "/home/bren/data/datanode-vol1"

---

# Data Node-2
apiVersion: v1
kind: PersistentVolume
metadata:
  name: datanode-vol2-pv
  labels:
      type: datanode-vol2
spec:
  capacity:
    storage: 200M
  accessModes:
    - ReadWriteOnce
  storageClassName: default
  hostPath:
      path: "/home/bren/data/datanode-vol2"

---

# Data Node-3
apiVersion: v1
kind: PersistentVolume
metadata:
  name: datanode-vol3-pv
  labels:
      type: datanode-vol3
spec:
  capacity:
    storage: 200M
  accessModes:
    - ReadWriteOnce
  storageClassName: default
  hostPath:
      path: "/home/bren/data/datanode-vol3"