# type: LoadBalancer | ClusterIP | NodePort
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.taskManager.appName }}
spec:
  selector:
    app: {{ .Values.taskManager.appName }}
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer