apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.taskManager.appName }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.taskManager.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.taskManager.appName }}
    spec:
      containers:
      - name: {{ .Values.taskManager.appName }}
        image: {{ .Values.taskManager.image }}
        env:
            - name: REDIS_SERVER
              value: {{ .Values.taskManager.redisHost }}
            - name: REDIS_PASS
              value: {{ .Values.taskManager.redisPass }}
            - name: REDIS_PORT
              value: "6379"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
