apiVersion: v1
kind: Service
metadata:
  name: namenode
spec:
  ports:
    - port: 8020
      protocol: TCP
      name: namenode-rpc
    - port: 80
      targetPort: 50070
      protocol: TCP
      name: namenode-web
  selector:
    app: namenode
  type: ClusterIP
