# YAML Validator:   https://www.yamllint.com/
# Valid Configs:    https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
# Best Practice:    https://kubernetes.io/docs/concepts/configuration/overview/
# Exposing Service: https://kubernetes.io/docs/tasks/access-application-cluster/port-forward-access-application-cluster/
apiVersion: v1
kind: Pod
metadata:
  name: simple-server-a
spec:
  containers:
    - name: simple-server-a
      image: bkenna/simple-server-app
      command: [ "/usr/local/bin/node" ] 
      args: [ "index.js", "--server", "Server-A", "--port", "8000" ]
      ports:
        - containerPort: 8000
      resources:
        limits:
          memory: "200M"
          cpu: "2"